name: Deploy to Amplify

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Amplify CLI
        run: npm install -g @aws-amplify/cli

      - name: Load Amplify Environment Variables
        run: |
          source amplify.env
          echo "AMPLIFY_MONOREPO_APP_ROOT=$AMPLIFY_MONOREPO_APP_ROOT" >> $GITHUB_ENV
          echo "AMPLIFY_APP_ID=$AMPLIFY_APP_ID" >> $GITHUB_ENV
          echo "AMPLIFY_ENV=$AMPLIFY_ENV" >> $GITHUB_ENV

      - name: Pull Amplify Backend
        run: amplify pull --app-id $AMPLIFY_APP_ID --env $AMPLIFY_ENV --yes

      - name: Verify Amplify Project Files
        run: ls -R $AMPLIFY_MONOREPO_APP_ROOT/amplify/ || echo "Amplify directory not found"

      - name: Deploy to Amplify
        run: amplify publish
