name: Trigger Amplify Webhook

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trigger Amplify Deployment via Webhook
        run: |
          curl -X POST "$DEPLOYMENT_WEBHOOK_URL"
