name: Release & Publish NPM Package

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Required to push tags & commits
      packages: write  # Required to publish to GitHub Packages

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures tags are fetched

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com/"
          scope: "@simaoptrocha"

      - name: Install Dependencies
        run: npm install

      - name: Bump Version & Push Tags
        run: |
          npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Package
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
